"""Contains 2020 State Data
All states are "Winner Take All" Except Main and Nebraska.
https://www.270towin.com/content/split-electoral-votes-maine-and-nebraska/
Total Votes by State Sourced:
https://en.wikipedia.org/wiki/United_States_Electoral_College#Chronological_table
"""
electoral_college = {
    "Alabama": 9,
    "Alaska": 3,
    "Arizona": 11,
    "Arkansas": 6,
    "California": 55,
    "Colorado": 9,
    "Connecticut": 7,
    "Delaware": 3,
    "District of Columbia": 3,
    "Florida": 29,
    "Georgia": 16,
    "Hawaii": 4,
    "Idaho": 4,
    "Illinois": 20,
    "Indiana": 11,
    "Iowa": 6,
    "Kansas": 6,
    "Kentucky": 8,
    "Louisiana": 8,
    "Maine": 2,
    "Maine CD-1": 1,
    "Maine CD-2": 1,
    "Maryland": 10,
    "Massachusetts": 11,
    "Michigan": 16,
    "Minnesota": 10,
    "Mississippi": 6,
    "Missouri": 10,
    "Montana": 3,
    "Nebraska": 3,
    "Nebraska CD-1": 1,
    "Nebraska CD-2": 1,
    "Nebraska CD-3": 1,
    "Nevada": 6,
    "New Hampshire": 4,
    "New Jersey": 14,
    "New Mexico": 5,
    "New York": 29,
    "North Carolina": 15,
    "North Dakota": 3,
    "Ohio": 18,
    "Oklahoma": 7,
    "Oregon": 7,
    "Pennsylvania": 20,
    "Rhode Island": 4,
    "South Carolina": 9,
    "South Dakota": 3,
    "Tennessee": 11,
    "Texas": 38,
    "Utah": 6,
    "Vermont": 3,
    "Virginia": 13,
    "Washington": 12,
    "West Virginia": 5,
    "Wisconsin": 10,
    "Wyoming": 3,
}

# Presedential Nominee By Party - 2020
nomineePartyMap = {'CON': "Blankenship, Don",
                   'DEM': "Biden, Joe",
                   'GRE': "Hawkins, Howie",
                   'IND': "Pierce, Brock",
                   'LIB': "Jorgenson, Jo",
                   'OTH': "OTHER",
                   'PSL': "La Riva, Gloria",
                   'REP': "Trump, Donald",
                   'SWP': "Kennedy, Alyson"}